def format_for_chatgpt(data):

    prompt = (
        f"**Team Analysis for {data['team_1_info'].get('team_name', 'N/A')} vs {data['team_2_info'].get('team_name', 'N/A')}**\n\n"

        f"**League Information:**\n"
        f"  - League Name: {data['league_info'].get('league_name', 'N/A')}\n"
        f"  - Country: {data['league_info'].get('country', 'N/A')}\n"
        f"  - Season: {data['league_info'].get('season', 'N/A')}\n"
        f"  - League Logo: {data['league_info'].get('logo', 'N/A')}\n"
        f"  - Country Flag: {data['league_info'].get('flag', 'N/A')}\n\n"
        
        f"**{data['team_1_info'].get('team_name', 'N/A')} Info:**\n"
        f"  - Team ID: {data['team_1_info'].get('team_id', 'N/A')}\n"
        f"  - Form: {data['team_1_info'].get('form', 'N/A')}\n"
        f"  - Logo: {data['team_1_info'].get('logo', 'N/A')}\n\n"
        
        f"**Fixtures for {data['team_1_info'].get('team_name', 'N/A')}**\n"
        f"  - Played: Home: {data['team_1_info']['fixtures']['played'].get('home', 'N/A')}, "
        f"Away: {data['team_1_info']['fixtures']['played'].get('away', 'N/A')}, Total: {data['team_1_info']['fixtures']['played'].get('total', 'N/A')}\n"
        f"  - Wins: Home: {data['team_1_info']['fixtures']['wins'].get('home', 'N/A')}, Away: {data['team_1_info']['fixtures']['wins'].get('away', 'N/A')}, "
        f"Total: {data['team_1_info']['fixtures']['wins'].get('total', 'N/A')}\n"
        f"  - Draws: Home: {data['team_1_info']['fixtures']['draws'].get('home', 'N/A')}, Away: {data['team_1_info']['fixtures']['draws'].get('away', 'N/A')}, "
        f"Total: {data['team_1_info']['fixtures']['draws'].get('total', 'N/A')}\n"
        f"  - Losses: Home: {data['team_1_info']['fixtures']['loses'].get('home', 'N/A')}, Away: {data['team_1_info']['fixtures']['loses'].get('away', 'N/A')}, "
        f"Total: {data['team_1_info']['fixtures']['loses'].get('total', 'N/A')}\n\n"
        
        f"**{data['team_2_info'].get('team_name', 'N/A')} Info:**\n"
        f"  - Team ID: {data['team_2_info'].get('team_id', 'N/A')}\n"
        f"  - Form: {data['team_2_info'].get('form', 'N/A')}\n"
        f"  - Logo: {data['team_2_info'].get('logo', 'N/A')}\n\n"
        
        f"**Fixtures for {data['team_2_info'].get('team_name', 'N/A')}**\n"
        f"  - Played: Home: {data['team_2_info']['fixtures']['played'].get('home', 'N/A')}, "
        f"Away: {data['team_2_info']['fixtures']['played'].get('away', 'N/A')}, Total: {data['team_2_info']['fixtures']['played'].get('total', 'N/A')}\n"
        f"  - Wins: Home: {data['team_2_info']['fixtures']['wins'].get('home', 'N/A')}, Away: {data['team_2_info']['fixtures']['wins'].get('away', 'N/A')}, "
        f"Total: {data['team_2_info']['fixtures']['wins'].get('total', 'N/A')}\n"
        f"  - Draws: Home: {data['team_2_info']['fixtures']['draws'].get('home', 'N/A')}, Away: {data['team_2_info']['fixtures']['draws'].get('away', 'N/A')}, "
        f"Total: {data['team_2_info']['fixtures']['draws'].get('total', 'N/A')}\n"
        f"  - Losses: Home: {data['team_2_info']['fixtures']['loses'].get('home', 'N/A')}, Away: {data['team_2_info']['fixtures']['loses'].get('away', 'N/A')}, "
        f"Total: {data['team_2_info']['fixtures']['loses'].get('total', 'N/A')}\n\n"

        f"**Goals for {data['team_1_info'].get('team_name', 'N/A')}**\n"
        f"  - Goals For: Home: {data['team_1_info']['goals']['for']['total'].get('home', 'N/A')}, "
        f"Away: {data['team_1_info']['goals']['for']['total'].get('away', 'N/A')}, Total: {data['team_1_info']['goals']['for']['total'].get('total', 'N/A')}\n"
        f"  - Goals Against: Home: {data['team_1_info']['goals']['against']['total'].get('home', 'N/A')}, "
        f"Away: {data['team_1_info']['goals']['against']['total'].get('away', 'N/A')}, Total: {data['team_1_info']['goals']['against']['total'].get('total', 'N/A')}\n"
        f"  - Average Goals For: {data['team_1_info']['goals']['for']['average'].get('total', 'N/A')}\n"
        f"  - Average Goals Against: {data['team_1_info']['goals']['against']['average'].get('total', 'N/A')}\n\n"
        f"  - Goals By Minute (For):\n"
        f"    - 0-15: {data['team_1_info']['goals']['for']['minute'].get('0-15', 'N/A')} goals\n"
        f"    - 16-30: {data['team_1_info']['goals']['for']['minute'].get('16-30', 'N/A')} goals\n"
        f"    - 31-45: {data['team_1_info']['goals']['for']['minute'].get('31-45', 'N/A')} goals\n"
        f"    - 46-60: {data['team_1_info']['goals']['for']['minute'].get('46-60', 'N/A')} goals\n"
        f"    - 61-75: {data['team_1_info']['goals']['for']['minute'].get('61-75', 'N/A')} goals\n"
        f"    - 76-90: {data['team_1_info']['goals']['for']['minute'].get('76-90', 'N/A')} goals\n"
        f"    - 91-105: {data['team_1_info']['goals']['for']['minute'].get('91-105', 'N/A')} goals\n\n"
                f"  - Goals By Minute (Against):\n"
        f"    - 0-15: {data['team_1_info']['goals']['against']['minute'].get('0-15', 'N/A')} goals\n"
        f"    - 16-30: {data['team_1_info']['goals']['against']['minute'].get('16-30', 'N/A')} goals\n"
        f"    - 31-45: {data['team_1_info']['goals']['against']['minute'].get('31-45', 'N/A')} goals\n"
        f"    - 46-60: {data['team_1_info']['goals']['against']['minute'].get('46-60', 'N/A')} goals\n"
        f"    - 61-75: {data['team_1_info']['goals']['against']['minute'].get('61-75', 'N/A')} goals\n"
        f"    - 76-90: {data['team_1_info']['goals']['against']['minute'].get('76-90', 'N/A')} goals\n"
        f"    - 91-105: {data['team_1_info']['goals']['against']['minute'].get('91-105', 'N/A')} goals\n\n"

        f"  - Under/Over Stats:\n"
        f"    - 0.5 Goals: Over {data['team_1_info']['under_over']['for'].get('0.5', {}).get('over', 'N/A')}, Under {data['team_1_info']['under_over']['for'].get('0.5', {}).get('under', 'N/A')}\n"
        f"    - 1.5 Goals: Over {data['team_1_info']['under_over']['for'].get('1.5', {}).get('over', 'N/A')}, Under {data['team_1_info']['under_over']['for'].get('1.5', {}).get('under', 'N/A')}\n"
        f"    - 2.5 Goals: Over {data['team_1_info']['under_over']['for'].get('2.5', {}).get('over', 'N/A')}, Under {data['team_1_info']['under_over']['for'].get('2.5', {}).get('under', 'N/A')}\n"
        f"    - 3.5 Goals: Over {data['team_1_info']['under_over']['for'].get('3.5', {}).get('over', 'N/A')}, Under {data['team_1_info']['under_over']['for'].get('3.5', {}).get('under', 'N/A')}\n"
        f"    - 4.5 Goals: Over {data['team_1_info']['under_over']['for'].get('4.5', {}).get('over', 'N/A')}, Under {data['team_1_info']['under_over']['for'].get('4.5', {}).get('under', 'N/A')}\n"

        f"**Goals for {data['team_2_info'].get('team_name', 'N/A')}**\n"
        f"  - Goals For: Home: {data['team_2_info']['goals']['for']['total'].get('home', 'N/A')}, "
        f"Away: {data['team_2_info']['goals']['for']['total'].get('away', 'N/A')}, Total: {data['team_2_info']['goals']['for']['total'].get('total', 'N/A')}\n"
        f"  - Goals Against: Home: {data['team_2_info']['goals']['against']['total'].get('home', 'N/A')}, "
        f"Away: {data['team_2_info']['goals']['against']['total'].get('away', 'N/A')}, Total: {data['team_2_info']['goals']['against']['total'].get('total', 'N/A')}\n"
        f"  - Average Goals For: {data['team_2_info']['goals']['for']['average'].get('total', 'N/A')}\n"
        f"  - Average Goals Against: {data['team_2_info']['goals']['against']['average'].get('total', 'N/A')}\n\n"
        f"  - Goals By Minute (For):\n"
        f"    - 0-15: {data['team_2_info']['goals']['for']['minute'].get('0-15', 'N/A')} goals\n"
        f"    - 16-30: {data['team_2_info']['goals']['for']['minute'].get('16-30', 'N/A')} goals\n"
        f"    - 31-45: {data['team_2_info']['goals']['for']['minute'].get('31-45', 'N/A')} goals\n"
        f"    - 46-60: {data['team_2_info']['goals']['for']['minute'].get('46-60', 'N/A')} goals\n"
        f"    - 61-75: {data['team_2_info']['goals']['for']['minute'].get('61-75', 'N/A')} goals\n"
        f"    - 76-90: {data['team_2_info']['goals']['for']['minute'].get('76-90', 'N/A')} goals\n"
        f"    - 91-105: {data['team_2_info']['goals']['for']['minute'].get('91-105', 'N/A')} goals\n\n"
                f"  - Goals By Minute (Against):\n"
        f"    - 0-15: {data['team_2_info']['goals']['against']['minute'].get('0-15', 'N/A')} goals\n"
        f"    - 16-30: {data['team_2_info']['goals']['against']['minute'].get('16-30', 'N/A')} goals\n"
        f"    - 31-45: {data['team_2_info']['goals']['against']['minute'].get('31-45', 'N/A')} goals\n"
        f"    - 46-60: {data['team_2_info']['goals']['against']['minute'].get('46-60', 'N/A')} goals\n"
        f"    - 61-75: {data['team_2_info']['goals']['against']['minute'].get('61-75', 'N/A')} goals\n"
        f"    - 76-90: {data['team_2_info']['goals']['against']['minute'].get('76-90', 'N/A')} goals\n"
        f"    - 91-105: {data['team_2_info']['goals']['against']['minute'].get('91-105', 'N/A')} goals\n\n"

        f"  - Under/Over Stats:\n"
        f"    - 0.5 Goals: Over {data['team_2_info']['under_over']['for'].get('0.5', {}).get('over', 'N/A')}, Under {data['team_2_info']['under_over']['for'].get('0.5', {}).get('under', 'N/A')}\n"
        f"    - 1.5 Goals: Over {data['team_2_info']['under_over']['for'].get('1.5', {}).get('over', 'N/A')}, Under {data['team_2_info']['under_over']['for'].get('1.5', {}).get('under', 'N/A')}\n"
        f"    - 2.5 Goals: Over {data['team_2_info']['under_over']['for'].get('2.5', {}).get('over', 'N/A')}, Under {data['team_2_info']['under_over']['for'].get('2.5', {}).get('under', 'N/A')}\n"
        f"    - 3.5 Goals: Over {data['team_2_info']['under_over']['for'].get('3.5', {}).get('over', 'N/A')}, Under {data['team_2_info']['under_over']['for'].get('3.5', {}).get('under', 'N/A')}\n"
        f"    - 4.5 Goals: Over {data['team_2_info']['under_over']['for'].get('4.5', {}).get('over', 'N/A')}, Under {data['team_2_info']['under_over']['for'].get('4.5', {}).get('under', 'N/A')}\n"

        f"**Key Stats for {data['team_1_info'].get('team_name', 'N/A')}**\n"
        f"  - Clean Sheets: Home: {data['team_1_info']['clean_sheet'].get('home', 'N/A')}, "
        f"Away: {data['team_1_info']['clean_sheet'].get('away', 'N/A')}, Total: {data['team_1_info']['clean_sheet'].get('total', 'N/A')}\n"
        f"  - Failed to Score: Home: {data['team_1_info']['failed_to_score'].get('home', 'N/A')}, "
        f"Away: {data['team_1_info']['failed_to_score'].get('away', 'N/A')}, Total: {data['team_1_info']['failed_to_score'].get('total', 'N/A')}\n"
        f"  - Most Frequent Formation: {data['team_1_info']['lineups'][0].get('formation', 'N/A')} (played {data['team_1_info']['lineups'][0].get('played', 'N/A')} times)\n\n"
        f"  - Lineups:\n"
        + "\n".join(
            [f"    - {lineup.get('formation', 'N/A')} (played {lineup.get('played', 'N/A')} times)"
             for lineup in data['team_1_info']['lineups']]
        ) + "\n\n"
        f"**Biggest Stats for {data['team_1_info'].get('team_name', 'N/A')}**\n"
        f"  - Streaks: Wins: {data['team_1_info']['biggest']['streak'].get('wins', 'N/A')}, Draws: {data['team_1_info']['biggest']['streak'].get('draws', 'N/A')}, Losses: {data['team_1_info']['biggest']['streak'].get('loses', 'N/A')}\n"
        f"  - Biggest Win: Home: {data['team_1_info']['biggest']['wins'].get('home', 'N/A')}, Away: {data['team_1_info']['biggest']['wins'].get('away', 'N/A')}\n"
        f"  - Biggest Loss: Home: {data['team_1_info']['biggest']['loses'].get('home', 'N/A')}, Away: {data['team_1_info']['biggest']['loses'].get('away', 'N/A')}\n"
        f"  - Goals For (Biggest): Home: {data['team_1_info']['biggest']['goals']['for'].get('home', 'N/A')}, Away: {data['team_1_info']['biggest']['goals']['for'].get('away', 'N/A')}\n"
        f"  - Goals Against (Biggest): Home: {data['team_1_info']['biggest']['goals']['against'].get('home', 'N/A')}, Away: {data['team_1_info']['biggest']['goals']['against'].get('away', 'N/A')}\n\n"

        f"**Key Stats for {data['team_2_info'].get('team_name', 'N/A')}**\n"
        f"  - Clean Sheets: Home: {data['team_2_info']['clean_sheet'].get('home', 'N/A')}, "
        f"Away: {data['team_2_info']['clean_sheet'].get('away', 'N/A')}, Total: {data['team_2_info']['clean_sheet'].get('total', 'N/A')}\n"
        f"  - Failed to Score: Home: {data['team_2_info']['failed_to_score'].get('home', 'N/A')}, "
        f"Away: {data['team_2_info']['failed_to_score'].get('away', 'N/A')}, Total: {data['team_2_info']['failed_to_score'].get('total', 'N/A')}\n"
        f"  - Most Frequent Formation: {data['team_2_info']['lineups'][0].get('formation', 'N/A')} (played {data['team_2_info']['lineups'][0].get('played', 'N/A')} times)\n\n"
                f"  - Lineups:\n"
        + "\n".join(
            [f"    - {lineup.get('formation', 'N/A')} (played {lineup.get('played', 'N/A')} times)"
             for lineup in data['team_2_info']['lineups']]
        ) + "\n\n"
        f"**Biggest Stats for {data['team_2_info'].get('team_name', 'N/A')}**\n"
        f"  - Streaks: Wins: {data['team_2_info']['biggest']['streak'].get('wins', 'N/A')}, Draws: {data['team_2_info']['biggest']['streak'].get('draws', 'N/A')}, Losses: {data['team_2_info']['biggest']['streak'].get('loses', 'N/A')}\n"
        f"  - Biggest Win: Home: {data['team_2_info']['biggest']['wins'].get('home', 'N/A')}, Away: {data['team_2_info']['biggest']['wins'].get('away', 'N/A')}\n"
        f"  - Biggest Loss: Home: {data['team_2_info']['biggest']['loses'].get('home', 'N/A')}, Away: {data['team_2_info']['biggest']['loses'].get('away', 'N/A')}\n"
        f"  - Goals For (Biggest): Home: {data['team_2_info']['biggest']['goals']['for'].get('home', 'N/A')}, Away: {data['team_2_info']['biggest']['goals']['for'].get('away', 'N/A')}\n"
        f"  - Goals Against (Biggest): Home: {data['team_2_info']['biggest']['goals']['against'].get('home', 'N/A')}, Away: {data['team_2_info']['biggest']['goals']['against'].get('away', 'N/A')}\n\n"

                f"**Cards for {data['team_1_info'].get('team_name', 'N/A')}**\n"
        f"  - Yellow Cards By Minute:\n"
        f"    - 0-15: {data['team_1_info']['cards']['yellow'].get('0-15', 'N/A')}\n"
        f"    - 16-30: {data['team_1_info']['cards']['yellow'].get('16-30', 'N/A')}\n"
        f"    - 31-45: {data['team_1_info']['cards']['yellow'].get('31-45', 'N/A')}\n"
        f"    - 46-60: {data['team_1_info']['cards']['yellow'].get('46-60', 'N/A')}\n"
        f"    - 61-75: {data['team_1_info']['cards']['yellow'].get('61-75', 'N/A')}\n"
        f"    - 76-90: {data['team_1_info']['cards']['yellow'].get('76-90', 'N/A')}\n"
        f"    - 91-105: {data['team_1_info']['cards']['yellow'].get('91-105', 'N/A')}\n\n"
        f"  - Red Cards: {data['team_1_info']['cards'].get('red', 'No red cards in any timeframe')}\n\n"
        
                f"**Cards for {data['team_2_info'].get('team_name', 'N/A')}**\n"
        f"  - Yellow Cards By Minute:\n"
        f"    - 0-15: {data['team_2_info']['cards']['yellow'].get('0-15', 'N/A')}\n"
        f"    - 16-30: {data['team_2_info']['cards']['yellow'].get('16-30', 'N/A')}\n"
        f"    - 31-45: {data['team_2_info']['cards']['yellow'].get('31-45', 'N/A')}\n"
        f"    - 46-60: {data['team_2_info']['cards']['yellow'].get('46-60', 'N/A')}\n"
        f"    - 61-75: {data['team_2_info']['cards']['yellow'].get('61-75', 'N/A')}\n"
        f"    - 76-90: {data['team_2_info']['cards']['yellow'].get('76-90', 'N/A')}\n"
        f"    - 91-105: {data['team_2_info']['cards']['yellow'].get('91-105', 'N/A')}\n\n"
        f"  - Red Cards: {data['team_2_info']['cards'].get('red', 'No red cards in any timeframe')}\n\n"

                f"**Penalty Stats Comparison**\n"
        f"  - {data['team_1_info'].get('team_name', 'N/A')} Penalties Scored: {data['team_1_info']['penalty']['scored'].get('total', 'N/A')} "
        f"({data['team_1_info']['penalty']['scored'].get('percentage', 'N/A')})\n"
        f"  - {data['team_1_info'].get('team_name', 'N/A')} Penalties Missed: {data['team_1_info']['penalty']['missed'].get('total', 'N/A')} "
        f"({data['team_1_info']['penalty']['missed'].get('percentage', 'N/A')})\n"
        
        f"  - {data['team_2_info'].get('team_name', 'N/A')} Penalties Scored: {data['team_2_info']['penalty']['scored'].get('total', 'N/A')} "
        f"({data['team_2_info']['penalty']['scored'].get('percentage', 'N/A')})\n"
        f"  - {data['team_2_info'].get('team_name', 'N/A')} Penalties Missed: {data['team_2_info']['penalty']['missed'].get('total', 'N/A')} "
        f"({data['team_2_info']['penalty']['missed'].get('percentage', 'N/A')})\n"
    )
    
    return prompt
